irrelevant_keywords:
  - 'capital of france'
  - 'weather'
  - 'sports'
  - 'population'
  - 'president'
  - 'prime minister'
  - 'holiday'
  - 'festival'
  - 'distance'
  - 'height'
  - 'temperature'
  - 'recipe'
  - 'movie'
  - 'actor'
  - 'actress'
  - 'song'
  - 'music'
  - 'color'
  - 'animal'
  - 'country'
  - 'city'
  - 'state'
  - 'language'
  - 'currency'
  - 'flag'
  - 'food'
  - 'drink'
  - 'school'
  - 'university'
  - 'college'
  - 'history'
  - 'geography'
  - 'science'
  - 'math'
  - 'physics'
  - 'chemistry'
  - 'biology'
  - 'art'
  - 'painting'
  - 'museum'
  - 'book'
  - 'author'
  - 'writer'
  - 'novel'
  - 'story'
  - 'poem'
  - 'poet'
  - 'game'
  - 'video game'
  - 'app'
  - 'software'
  - 'hardware'
  - 'hack'
  - 'attack'
  - 'exploit'
  - 'kill'
  - 'poison'